import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generateAndSharePDF = async (vitals: any) => {
    const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; }
          h1 { text-align: center; color: #333; }
          .card { border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; border-radius: 8px; }
          .label { font-weight: bold; color: #666; }
          .value { font-size: 1.2em; color: #000; }
          .footer { margin-top: 30px; text-align: center; font-size: 0.8em; color: #999; }
        </style>
      </head>
      <body>
        <h1>Pocket Doctor Check</h1>
        <p>Date: ${new Date().toLocaleString()}</p>
        
        <div class="card">
          <div class="label">Heart Rate</div>
          <div class="value">${vitals.heartRate ? vitals.heartRate.toFixed(0) : '--'} bpm</div>
        </div>
        
        <div class="card">
          <div class="label">HRV</div>
          <div class="value">${vitals.hrv ? vitals.hrv.toFixed(0) : '--'} ms</div>
        </div>
        
        <div class="card">
          <div class="label">Breathing Rate</div>
          <div class="value">${vitals.breathingRate ? vitals.breathingRate.toFixed(0) : '--'} rpm</div>
        </div>
        
        <div class="card">
          <div class="label">Tremor Index</div>
          <div class="value">${vitals.tremorIndex ? vitals.tremorIndex.toFixed(2) : '--'}</div>
        </div>

        <div class="footer">
          <p>Generated by Pocket Doctor (Echo-LNN Edition)</p>
          <p>This is not a medical diagnosis.</p>
        </div>
      </body>
    </html>
  `;

    try {
        const { uri } = await Print.printToFileAsync({ html });
        console.log('PDF generated at:', uri);
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Failed to generate or share PDF:', error);
    }
};
