import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export const generateAndSharePDF = async (vitals: any) => {
    const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; }
          h1 { text-align: center; color: #333; }
          h2 { color: #555; margin-top: 25px; }
          .triage { 
            background: #f0f8ff; 
            padding: 15px; 
            margin-bottom: 20px; 
            border-radius: 8px; 
            border-left: 4px solid ${vitals.triageSeverity === 'green' ? '#4CAF50' : vitals.triageSeverity === 'yellow' ? '#FFC107' : '#F44336'};
          }
          .card { border: 1px solid #ddd; padding: 15px; margin-bottom: 10px; border-radius: 8px; }
          .label { font-weight: bold; color: #666; }
          .value { font-size: 1.2em; color: #000; margin-top: 5px; }
          .recommendation { margin-left: 20px; margin-bottom: 5px; }
          .footer { margin-top: 30px; text-align: center; font-size: 0.8em; color: #999; }
        </style>
      </head>
      <body>
        <h1>Pocket Wellness Check</h1>
        <p>Date: ${new Date().toLocaleString()}</p>
        
        ${vitals.triageSummary ? `
          <div class="triage">
            <h2>Assessment</h2>
            <p>${vitals.triageSummary}</p>
            ${vitals.triageRecommendations && vitals.triageRecommendations.length > 0 ? `
              <h3>Recommendations:</h3>
              ${vitals.triageRecommendations.map((rec: string) => `<p class="recommendation">• ${rec}</p>`).join('')}
            ` : ''}
          </div>
        ` : ''}
        
        <h2>Vital Signs</h2>
        
        <div class="card">
          <div class="label">Heart Rate</div>
          <div class="value">${vitals.heartRate ? vitals.heartRate.toFixed(0) : '--'} bpm</div>
        </div>
        
        <div class="card">
          <div class="label">HRV (Heart Rate Variability)</div>
          <div class="value">${vitals.hrv ? vitals.hrv.toFixed(0) : '--'} ms</div>
        </div>
        
        <div class="card">
          <div class="label">Breathing Rate</div>
          <div class="value">${vitals.breathingRate ? vitals.breathingRate.toFixed(0) : '--'} rpm</div>
        </div>
        
        <div class="card">
          <div class="label">Tremor Index</div>
          <div class="value">${vitals.tremorIndex ? vitals.tremorIndex.toFixed(2) : '--'}</div>
        </div>
        
        ${vitals.coughType ? `
          <div class="card">
            <div class="label">Cough Type</div>
            <div class="value">${vitals.coughType}</div>
          </div>
        ` : ''}

        <div class="footer">
          <p>Generated by Pocket Wellness (Echo-LNN Edition)</p>
          <p><strong>This is not a medical diagnosis.</strong> Consult a healthcare professional for medical advice.</p>
        </div>
      </body>
    </html>
  `;

    try {
        const { uri } = await Print.printToFileAsync({ html });
        console.log('PDF generated at:', uri);
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('Failed to generate or share PDF:', error);
    }
};
